version: "3.8"

services:
  postgres:
    image: postgres:latest
    env_file: [.env.dev]
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 3s
      timeout: 3s
      retries: 3

  app:
    build:
      context: .
    env_file: [.env.dev]
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      POSTGRES_HOST: postgres
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:${APP_PORT}/actuator/health"]
      interval: 3s
      timeout: 3s
      retries: 5
