version: "3.8"

services:
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - app

  app:
    image: jidak/inssider-be-main:1.0.0
    restart: "on-failure"
    env_file: [.env.prod]
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "${APP_PORT}:${APP_PORT}"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:${APP_PORT}/actuator/health"]
      interval: 30s
      timeout: 3s
      retries: 3
