server.port: ${APP_PORT}

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

spring.jpa.open-in-view: false
spring.jpa.hibernate.ddl-auto: none

management.endpoints.web.exposure.include: health
