name: Publish Docker image on Semver tag push

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILD_RECORD_RETENTION_DAYS: 1
    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5.7.0
        with:
          images: |
            ${{ vars.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Login to Docker Hub
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ vars.DOCKERHUB_ID }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/setup-buildx-action@v3.10.0

      - name: Build and push
        uses: docker/build-push-action@v6.17.0
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags || 'latest' }}
          labels: ${{ steps.meta.outputs.labels }}
